export const TUTORIAL_CREATE = 'TUTORIAL_CREATE';
export const TUTORIALS_FETCH = 'TUTORIALS_FETCH';
export const TUTORIAL_UPDATE = 'TUTORIAL_UPDATE';
export const TUTORIAL_DELETE = 'TUTORIAL_DELETE';
export const ALL_TUTORIALS_DELETE = 'ALL_TUTORIALS_DELETE';
